version: "3.9"

services:
  bot:
    build: .
    container_name: my-tgbot
    working_dir: "/usr/src/app/tg_bot"
    volumes:
    - .:/usr/src/app/tg_bot
    command: python3 -m main
    restart: always
    env_file:
      - ".env"
    networks:
      - tg_bot

  db:
    image: postgres:17.2
    container_name: coursework-2-17.2
    restart: always
    env_file: .env

    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_NAME

    ports:
      - ${DB_PORT}:5432

    volumes:
      - db_data:/var/lib/postgresql/data
    
    networks:
      - tg_bot
  
  tests:
    build: .
    container_name: tgbot-tests
    working_dir: "/usr/src/app"
    volumes:
      - .:/usr/src/app
    command: >
      sh -c "PYTHONPATH=/usr/src/app pytest
      app/voice_processing/test/
      database_vm/test/
      -v
      --cov=app/voice_processing
      --cov=database_vm
      --cov-report=term-missing"
    env_file:
      - ".env"
    depends_on:
      - db
    networks:
      - tg_bot
    deploy:
      resources:
        limits:
          memory: 5G
          cpus: '1.5'
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  db_data:

networks:
  tg_bot:
    driver: bridge