version: "3.9"

services:
  bot:
    build: .
    container_name: my-tgbot
    working_dir: "/usr/src/app/tg_bot"
    volumes:
    - .:/usr/src/app/tg_bot
    command: python3 -m main
    restart: always
    env_file:
      - ".env"
    networks:
      - tg_bot

  db:
    image: postgres:17.2
    container_name: coursework-2-17.2
    restart: always
    env_file: .env

    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_NAME

    ports:
      - ${DB_PORT}:5432

    volumes:
      - db_data:/var/lib/postgresql/data
    
    networks:
      - tg_bot


volumes:
  db_data:

networks:
  tg_bot:
    driver: bridge